feat: tutorials-integration
readmeio/api-explorer pull request #958
Opened 2020-09-23 23:42 UTC by gratcliff

## 🧰 What's being changed?

Describe in detail what this PR is for.

## 🧪 Testing

Provide as much information as you can on how to test what you've done.

2020-10-15 22:42 UTC, gratcliff commented
Todo:
1. Reduce bundle size via optimizing transpiled `@readme/ui` output
2. Include exported `context` to populate our `@readme/variables` in the `syntax-highlighter`
3. Potentially add advertising callouts.

2020-10-19 23:38 UTC, runnabro commented
@gratcliff Some padding + overflow

<img width="969" alt="Screen Shot 2020-10-19 at 4 37 34 PM" src="https://user-images.githubusercontent.com/5341618/96522983-6c9b2c80-1229-11eb-8bd1-3181610fb194.png">

2020-10-20 00:53 UTC, gratcliff commented
> @gratcliff Some padding + overflow
> 
> <img alt="Screen Shot 2020-10-19 at 4 37 34 PM" width="969" src="https://user-images.githubusercontent.com/5341618/96522983-6c9b2c80-1229-11eb-8bd1-3181610fb194.png">

Nice!! Looks great. Do they scroll horizontally?

2020-10-20 01:16 UTC, runnabro commented
@gratcliff yeah, they do (tested on chrome, ff, safari)

2020-10-21 18:57 UTC, erunion requested changes
I added an experiment to the demo app for making tutorials visible but when clicking on one, a `codeOptions` error is thrown from the `TutorialModal` component. Not sure if this'll happen when the explorer is running in a non-demo app, if it's a problem with the fake tutorial data or what.

![Screen Shot 2020-10-21 at 11 54 59 AM](https://user-images.githubusercontent.com/33762/96769852-8d33c580-1394-11eb-9844-8bbef12cb72e.png)

2020-10-21 19:01 UTC, gratcliff commented
> I added an experiment to the demo app for making tutorials visible but when clicking on one, a `codeOptions` error is thrown from the `TutorialModal` component. Not sure if this'll happen when the explorer is running in a non-demo app, if it's a problem with the fake tutorial data or what.
> 
> ![Screen Shot 2020-10-21 at 11 54 59 AM](https://user-images.githubusercontent.com/33762/96769852-8d33c580-1394-11eb-9844-8bbef12cb72e.png)

@erunion looks like you'll need the full `tutorial` example object to see the `modal`, I may have led you astray in our slack chat!

2020-10-21 19:15 UTC, gratcliff commented on packages/api-explorer/src/Doc.jsx
> +            <div className="TutorialTile-Container">
Fixed this padding issue!

2020-10-21 19:15 UTC, gratcliff commented
@erunion fixed the `tutorial modal` demo issue by updating to a full schema reference. Also added in additional check in the demo to wipe the `doc.tutorials` array so that our state would update properly.

2020-10-21 20:52 UTC, erunion approved these changes

2020-10-21 21:02 UTC, merged